image: microsoft/dotnet:latest

stages:
  - build
  # - test
  - deploy

build_job:
  tags: 
    - dotnet
  stage: build
  artifacts:
    paths:
      - 'bin/Release/netcoreapp2.1/publish'
  script:
    - 'dotnet restore'
    - 'dotnet build -c Release'
    - 'dotnet publish -c Release'
    - 'sonar-scanner -Dproject.settings=bin/Release/netcoreapp2.1/publish/sonar-project.properties -Dsonar.login=$SQ_LOGIN -Dsonar.host.url=$SQ_URL -Dsonar.analysis.mode=publish -Dsonar.gitlab.commit_sha=%CI_COMMIT_SHA% -Dsonar.gitlab.ref_name=%CI_COMMIT_REF_NAME%'

# test_job:
#   stage: test
#   script:
#     - 'dotnet test tests/UnitTests'
#     - 'dotnet test tests/IntegrationTests'
#     - 'dotnet test tests/FunctionalTests'
#   dependencies:
#     - build_job

deploy_job:
  tags: 
    - dotnet
  stage: deploy
  artifacts:
    paths:
      - 'bin/Release/netcoreapp2.1/publish'
  script:
  - 'cf login -a https://api.run.pivotal.io -u $CF_USERNAME -p $CF_PASSWORD -s Development -o NTTD-PCF-ES-org'
  - 'cf push -f devops-gitlab-manifest.yml'
  dependencies:
    - build_job
    # - test_job
