image: microsoft/dotnet:latest

stages:
  - build
  # - test
  - deploy

build_job:
  tags: 
    - dotnet
  stage: build
  artifacts:
    paths:
      - 'bin/Release/netcoreapp2.1/publish'
  script:
    - 'dotnet restore'
    - 'dotnet build '
    - 'dotnet publish'

# test_job:
#   stage: test
#   script:
#     - 'dotnet test tests/UnitTests'
#     - 'dotnet test tests/IntegrationTests'
#     - 'dotnet test tests/FunctionalTests'
#   dependencies:
#     - build_job

deploy_job:
  tags: 
    - dotnet
  stage: deploy
  artifacts:
    paths:
      - 'bin/Release/netcoreapp2.1/publish'
  script:
  - 'cd bin/Release/netcoreapp2.1/publish'
  - 'cf login -a https://api.run.pivotal.io -u $CF_USERNAME -p $CF_PASSWORD -s Development -o NTTD-PCF-ES-org'
  - 'cf push'
  dependencies:
    - build_job
    # - test_job
